spring:
  application:
    name: video-backend

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true

server:
  port: 8080

# NCP Object Storage 설정
ncp:
  object-storage:
    endpoint: https://kr.object.ncloudstorage.com
    region: kr-standard
    access-key: ${NCP_ACCESS_KEY}
    secret-key: ${NCP_SECRET_KEY}
    bucket-name: video-upload-dev